title: Project Nirvana 2027
description: Wild camps with bonfire nights, natural farming with indigenous seeds, huts & caf√©. Build the tribe.
url: http://127.0.0.1:4000
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
permalink: /:categories/:title/
defaults:
  - scope: { path: "" }
    values: { layout: page }
  - scope: { path: "index.md" }   # keep the home hero using default
    values: { layout: default }